server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wall?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: ××××××

  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB


SavePath:
  ProfilePhoto: 'D:/java/*****/wall/src\main/resources/images/'  #图标存储路径
  ProfilePhotoMapper: 'profilePhoto/'  #图标的映射路径



mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.wall.**.domain
  mapper-locations: classpath*:mapper/*Mapper.xml

# 日志配置
logging:
  level:
    com.wall: debug
    org.springframework: warn

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: nailings123
  # 令牌有效期（默认30分钟）
  expireTime: 60


